# -*- coding: utf-8 -*-
"""comp_math1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QkmDC-sTaAP3BpLSz9Lqrcomihtz8BxZ
"""

import math
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
import sympy

"""#**Лабораторная работа №1.**
## **Вариант 4**
1.Используя библиотеку NumPy, создать матрицу 7x7 случайных целых принадлежащих отрезку [0, 10]. Транспонировать. Вычислить её определитель.
"""

A = np.random.randint(0,10,(7, 7))
print(A)
transposedA = A.transpose()
print(transposedA)
det = np.linalg.det(transposedA)
print(det)

"""2. Используя библиотеку NumPy, создать две матрицы под
ходящих размеров. Выполнить умножение матриц.

---


"""

B = np.array([[1, 2, 6], [4, 5, 1], [9, 1, 1]], int)
C = np.array([[5], [0], [8]], int)
D = np.dot(B, C)
print("B = ", B)
print("C = ", C)
print("B*C = ", D)

"""3. Используя библиотеку SymPy, упростите выражение ((2a+3b)^2 + (a/b)) и найдите его значение при a = sqrt(3), b = sqrt(7)."""

a, b = sympy.symbols("a b")
expr = (2*a + 3*b)** 2 + (a/b)
expr

res = expr.subs({a: sympy.sqrt(3), b: sympy.sqrt(7)}).evalf()
res

"""4. Используя библиотеку SymPy, найдите частные производ
ные от выражения из задания выше.
"""

diff_a = sympy.diff(expr, a)
diff_a

diff_b = sympy.diff(expr, b)
diff_b

"""5.Решить систему уравнений двумя способами: используя
библиотеку NumPy и библиотеку SymPy
$$
\begin{cases}
3X_1 + 2X_2 + X_3 = 5 \\
3X_1 + 3X_2 + 2X_3 = 7 \\
5X_1 + 5X_2 + 3X_3 = 11
\end{cases}
$$
"""

L = np.array([[3, 2, 1],
              [3, 3, 2],
              [5, 5, 3]])
R = np.array([5, 7, 11])
np_sol = np.linalg.solve(L, R)
np_sol

x1, x2, x3 = sympy.symbols("x1 x2 x3")
eq1 = sympy.Eq(3*x1 + 2*x2 + x3, 5)
eq2 = sympy.Eq(3*x1 + 3*x2 + 2*x3, 7)
eq3 = sympy.Eq(5*x1 + 5*x2 + 3*x3, 11)
sympy_sol = sympy.solve((eq1, eq2, eq3), (x1, x2, x3))
sympy_sol

"""6.Вычислить интеграл двумя способами: используя библиотеку SciPy и библиотеку SymPy $$ \int _0 ^{\pi/4}{\frac {1}{(1+2sin^2x)}} dx$$"""

sci_int = sp.integrate.quad(lambda x: 1/(1 + 2 * np.sin(x)**2), 0, math.pi/4)
sci_int

x = sympy.Symbol("x")
eqq = 1/(1 + 2 * sympy.sin(x)**2)
sympy.Integral(eqq, x)

sympy_int = sympy.integrate(eqq, (x, 0, sympy.pi/4))
sympy_int

"""7. Вычислить интеграл двумя способами: используя библио
теку SciPy и библиотеку SymPy $$\int_{-1}^{2} dy \int_{y^2}^{y+2} y^2 \,dx$$

"""

def f(x, y):
    return y**2
def h(y):
    return y + 2
v, err = sp.integrate.dblquad(f, -1, 2, lambda y: y**2, h)

print(v)

x, y = sympy.symbols("x y")
sympy.integrate(y**2, (x, y**2, y + 2), (y, -1, 2))

"""8.Построить в одной системе координат графики функций: y = 1 - сos(x), y = sqrt(3-x)
Оси координат должны быть подписаны, графики должны быть разного цвета, должна быть выведена легенда. Точку пересечения (если она есть) выделить на графике оранжевым цветом.
"""

def f1(x):
  return 1 - np.cos(x)
def f2(x):
  return np.sqrt(3 - x)

x_range = np.linspace(-np.pi*2, 3, 1000)

y1 = f1(x_range)
y2 = f2(x_range)

diff = np.abs(y1 - y2)
min_idx = np.argmin(diff)
x_intersect = x_range[min_idx]
y_intersect = y1[min_idx]


plt.figure(figsize=(10, 6))
plt.plot(x_range, y1, 'pink', linewidth=2, label='1 - cos(x)')
plt.plot(x_range, y2, 'grey', linewidth=2, label='√(3-x)')
plt.plot(x_intersect, y_intersect, 'o', color='orange', markersize=10,
         label=f'Пересечение ({x_intersect:.3f}, {y_intersect:.3f})')
plt.grid(True, alpha=0.3)
plt.legend()
plt.xlabel('x')
plt.ylabel('y')
plt.title('Графики функций')
plt.show()